### PR TITLE
fix: Observe the shadow dom changes

### PR DESCRIPTION
**Pull request by aui**
Thanks for your efforts on this project!

This PR is to fix async created builtin elements in shadow dom not working.

BUG Demo:

```js
import "@webreflection/custom-elements-builtin";

customElements.define(
  "web-link",
  class extends HTMLAnchorElement {
    constructor() {
      super();
      this.style.color = "red";
    }
  },
  {
    extends: "a"
  }
);

customElements.define(
  "web-widget",
  class extends HTMLElement {
    constructor() {
      super();
      this.attachShadow({ mode: "open" });
      setTimeout(() => {
        // a[is=web-link] not working..
        this.shadowRoot.innerHTML = '<a is="web-link" href="/">hello2</a>';
      }, 1000);
    }
  }
);

document.body.appendChild(document.createElement("web-widget"));
```

[Online demo(Safari)](https://codesandbox.io/s/dark-hooks-pgm2ux?file=/src/index.js)

Thanks for considering this fix.

### CODE REVIEW

**Comment by WebReflection** [comment]
@aui I don't understand what's the change here ... you just moved code around ... can you please elaborate what is this? Thanks!

**Comment by WebReflection** [comment]
also ... this module is called `@webreflection/custom-elements-builtin` ...

**Comment by aui** [comment]
> @aui I don't understand what's the change here ... you just moved code around ... can you please elaborate what is this? Thanks!

The only really effective part of this PR is this sentence:

````js
const {attachShadow} = Element.prototype;
````

I moved it to run after `qsaObserver({ ... })` .

This is because the `qsaObserver` function internally overrides the `Element.prototype.attachShadow` method (see here [#L58-L64](https://github.com/WebReflection/qsa-observer/blob/master/esm/index.js#L58-L64)), so moving the code allows you to get the `attachShadow` defined by `qsaObserver`.

I updated the BUG demo code: https://codesandbox.io/s/dark-hooks-pgm2ux?file=/src/index.js

thank you for replying!

**Comment by WebReflection** [comment]
@aui thanks ... reason I wasn't sure is that there was another issue coming from qsaObserver so locally nothing was working. This is now patched and I am patching dependent projects as I write.

Thanks for your patience and effort 👍

**Pull request closed without merging**
